apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-sandbox
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.149.0
      helm:
        releaseName: otel-collector
        valueFiles:
          - $values/helm-values/opentelemetry-collector.yaml
          - $values/helm-values/sandbox/opentelemetry-collector.yaml
    - repoURL: https://github.com/radoslavirha/home-server2
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sandbox
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      prune: true
