apiVersion: ENC[AES256_GCM,data:0IE=,iv:OdSBaMc7AOY9+8+79ePNc0CPLTpwsyYSVqLUxJMwjQQ=,tag:OTD536+Dqj+m03Ugfyqq8w==,type:str]
kind: ENC[AES256_GCM,data:aHeTaf3z,iv:oIldpQ1zyjC4LxvRP6XCkSjNYWo792+fatjllkC6W78=,tag:6MjKt9HDnUcF/IJV6f1gNw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HNVPUrgcoONXppL2trndqQ==,iv:KvdA6FiZz+xMMY8JqS6LlIRAKDIUUHf+SxnNOVQkmXw=,tag:FlzBAGiqP/QBSJ9eLNrJHw==,type:str]
    namespace: ENC[AES256_GCM,data:Mv1swA==,iv:CIE/ZSy/3DQQ3VlGztmUVjtmcz+CQX4wO36Xv/JBoGk=,tag:s0cC3984nD4QdUY1Ks2JJQ==,type:str]
type: ENC[AES256_GCM,data:XXsn/y0W,iv:qDPP1jYPwo5W+lNiW/VabhTIPQS4uhVwVMfLt/qoZe8=,tag:5pgh9TlvryUBtDwgHqLrjA==,type:str]
stringData:
    EMQX_DASHBOARD__DEFAULT_PASSWORD: ENC[AES256_GCM,data:aT5++h+entPR1YZW6CZ2Gb6ONYsg8gqj,iv:2hTcovcAznuuVi5RohBaOhsYhL3R6uJ+jGZYnsz8Q6k=,tag:/IyL01HdFr1hH7ALVFI85g==,type:str]
    EMQX_DASHBOARD__DEFAULT_USERNAME: ENC[AES256_GCM,data:R7kFoPQ=,iv:59xpdweehfEarRT8HJZDjKvb2i5I+mJqU2hnDDg8KWs=,tag:DOtQi5ft7VFMKGAuqcVAVA==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKemxvbTFHbExMTTBwRzdl
            TlIwcm1MU2E0b0o2NEpURXd4ejJoUnp5cjNNCmMzSnFkZmN1cTFVMGgvMjZMYmRZ
            R1JXWlpqcUdqd1hja2UvMmkzZXhSSUkKLS0tIDZ5R3JLUkJKM2lVR2xVMjNxano0
            N0ZQNVk4S2ZKWVo2M1ZMaThlVmU4TFkKhAhMJ0g7pYflrrDCieoos3E052x+DZ0H
            LB4wIlAWPHlo5iSGHLKZzeWIWfHU3t63ZtHQdwJCFSStGvYSNctd2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:15:56Z"
    mac: ENC[AES256_GCM,data:DMlNLDL3IY3fXMNr+pppI6fAOnnCFlRnB/DyKvFq5E/rnerqGu8wlUfLnLChe6qtdJXzfNjb7TUXbhWtxjZbvoMNvutzbk0dmcz2oal5HKEuwSaYb3AdpuIULvnxEYofiqItsb0WRIVnuhF8/2BfULqVNQ6sDnYEe78OMxWUQ8U=,iv:YrKfu7mDXjLllwxjntCiVJLXXTLXxkFWFTv6sL3tqtk=,tag:tpYalE7sCnNcKzd65UDQbg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
