apiVersion: ENC[AES256_GCM,data:wKk=,iv:xFQKUEDIZol/59cN9vYQUpf4w+ZB1GYbee7A3UBu2eY=,tag:i62fWir3f6Gn5UIWsprhcQ==,type:str]
kind: ENC[AES256_GCM,data:Osa+CWYZ,iv:38kXhBJi894p81Q5sM9YPwXfK3KHpWu5PhFCBsnP1Wc=,tag:nVEcfXtCLM5xb1izz2fBPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QPZ6Cc2fs0A5+or3hBwM7x/SmlnhVrMTBMfNA1v1b+s=,iv:nKqDtNjZJ+pfKg6pH2JZMa2FlUg8qYS32YP0TO5htTo=,tag:O7fYWOkzPBkKKyOa/tGhjg==,type:str]
    namespace: ENC[AES256_GCM,data:rmQ3u2hrhVBUQA==,iv:pPngRlNORzZ8Zf7hd7r1KHMyeO/b2FMdxVoeEUM1A0M=,tag:2k5+YcCH74Vm3DeDpYm8fQ==,type:str]
type: ENC[AES256_GCM,data:o6SZj5K7,iv:YiDJnmAYgci0ephJT71AmxeINYv5WMhoN4FsFVnGRG8=,tag:wBOOcex4xAOCBAqyG3AwKw==,type:str]
stringData:
    SECRET_MQTT_MIOT_BRIDGE_USERNAME: ENC[AES256_GCM,data:Twn2K4FOFfc/mUHL3+6SYA==,iv:/EDmRysW/wKeJN/hZTFCYXzWa/1a5skpVxSaflzy8dc=,tag:gTY6cf4Y0PWEd3vGz2QIMg==,type:str]
    SECRET_MQTT_MIOT_BRIDGE_PASSWORD: ENC[AES256_GCM,data:bMsVb9syn7WX79uk2ugaXmuTqIeBFGo+wZWutbKZXbzvyRoEUq1TYHfNBEk=,iv:heRpEjoWNjY86Xzv4wAkSdi8rx/InlXH16J9WWN70Pw=,tag:n6mvTRD5lF77/RG0rhQm8A==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVUg0c3A5VEEyeCtmVG5W
            VVlRd293VGxpTmNBNDRvRjhsVThQSWk5eXp3ClRTcTJLZ3BKMU9EWWl0Wlg5S3ZG
            bjZUWEZob1h5czhKQjE3bWp0RHJPQlUKLS0tIFBtU2lnT2UwdkQ2SGU0QTcrWk5D
            ay9vd1EwbFdMc1VickgyTzBRV2FuTncKzPDWmrTfM//kAOvlzNjAGNzqWxKkCJ2Z
            UQoPsPHvYHo7lMs8dCWv7ShHaCMVrz1DLpWAoT6JIsRlBVW7Gt9Ivw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:26:42Z"
    mac: ENC[AES256_GCM,data:AreCLGcNp6VKtgcB8P0RNrPKalMl3abJLQN9aeDGb+V+jIXDnGCPG5aA8ttO7nVdcEF5JjIQmCe8EXBpmzy2qeNiePGubtZMps4sozlyH5uG5SsD4zvpOf/SM5pO8vresgz/IqE2IMngxZm1oSgsnsR9cJIsOPBIOHI9MIxS+PQ=,iv:HJqwRv3C9MtvxCsd8DvSmH4Zk7kh1akjpO6ec4nC6zk=,tag:USRbriZr3RiUVDStALvtxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
