apiVersion: ENC[AES256_GCM,data:xyc=,iv:6gTLjJBLcq7PMDARIOa0EgMi/aiZbX63dKkgHVX0adU=,tag:x5+HD6sTm3rwK/kNzKx0yQ==,type:str]
kind: ENC[AES256_GCM,data:nmy/vBgO,iv:ksCwklq9HZBPEgdM7vgi6Sj75qMxfiDINQITmP8D7cc=,tag:exurehA/fED8I5piJCZ+zg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GiCeB2VTdmgOQdKkSP7N48WE3PeSSxathpqL7ReqSFjppsU=,iv:LH+wlxazNmUz1v50muYkvI9/YR87Q4isCYLQcX4S+uU=,tag:Lp5OIOfeeLFCvy73lUy5Cw==,type:str]
    namespace: ENC[AES256_GCM,data:xRRsDQddwpPgRg==,iv:hJoTNjQmjEUTbGaDUChaMr/Sjbdk10Bv5jHw0jnMioA=,tag:m5nRfsmyL2R9JvTGtpSX0w==,type:str]
type: ENC[AES256_GCM,data:6nNJnLQA,iv:pRXdQruxpYcMYPToABdpiTpPBkowxBCXs0Tz9oWQKbw=,tag:ymBh7L0RHe7oTMBPfmXvtw==,type:str]
stringData:
    SECRET_MONGODB_DATABASE: ENC[AES256_GCM,data:c3s80dTkiHxciUw=,iv:wZAYooUF1JUJBT5eH81cUpAqs9u84SlI55AYYVMVs4c=,tag:y/AQnM28Gq/ZFkf2p5hocw==,type:str]
    SECRET_MONGODB_PASSWORD: ENC[AES256_GCM,data:meLphxTESsRDRW91JsENbgyx0qxK8cqf,iv:unlsj+rEG9q5UsfZK2oRRSh24pCRsNWT2l36Dlb1cw0=,tag:cdtqBNcY3BDO84QfOnlRVQ==,type:str]
    SECRET_MONGODB_USERNAME: ENC[AES256_GCM,data:wFvpv83zeRjlZp4BtA4W,iv:lftkASmo16910TaQ/5mULy8CA7DIzahBhwEH5RMBkOo=,tag:MrrzsQ5LBxDD8Li0I4m+LQ==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbzk0QU9KM0V5UkpFZzA3
            MC83cGZndi9zMDdtNDh1ZWdyZ3ZlWHRPRndvClVHODM0ZXFlaDNHSlo4Wk5jay81
            V2VBa3VmT1QvT281ZkNDTmtTN3RzOFEKLS0tIDBuM1FtOHZaOHNJWXlEWTVZWWNO
            WHhaYmxLREMxTEFmWmcrRTNQVFRsVUEKO9ABVb6Bl5YFo+OQOkRjtepBxsUYHgMW
            B8Uv/fGpEQqiYt3KQ8I/JcEcqOvp+rDkP7hcCIBDIXpT3eEPb6166g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:26:36Z"
    mac: ENC[AES256_GCM,data:ujrg5DY/n0caLtEVhC7IZcXs64X5uj8wemr8qLE0ZUajcykSYohkxyz7+Yst8IrOsop33aEa1jtPXOeXQCbmOa6ucC9rWM5G0JlilGEhl4/Ijno91TPST0GJmn0PpG+NYCf20pIZG0zgUSxMOzBKiI+IhAJFbnIJ4MF3qF8IGT4=,iv:+ifhRkmZTaI4UfdTX3qxZUzhCBa2QzSVY3tcd3f1lVQ=,tag:D7FVvu1lw7Ev5Q6TikbUVg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
