apiVersion: ENC[AES256_GCM,data:4SA=,iv:CWumd3Mz9yzu2ZqcAE1xhbYK/FqKZ+gDKG5x2riSlj8=,tag:K5DnFJv3ksJ8TYk3rX55Pw==,type:str]
kind: ENC[AES256_GCM,data:rs/o68ja,iv:i5uib/TyTDq4gdihMUBtereQX2wP5QHzAh41TruvX2w=,tag:Xh/NE5VmAnSQpD91Jr4uaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9sOS4ej9vu7Fgkm6ULCiN1I=,iv:O57m+micKyy4jdci/ud6IoT2yC4AIJniU0bynH6kLq8=,tag:EhoERnyzDJlDET7u8wCOXQ==,type:str]
    namespace: ENC[AES256_GCM,data:i6AfFu6UJfsVzoLp,iv:ZNa/XErBfSraiIWKnd4Czcj789edEynhBp8zxGYJcSY=,tag:dVQsshEOGEEzz1OM+7Kphg==,type:str]
type: ENC[AES256_GCM,data:irP0AGZn,iv:iR5gltbHhaW9KHwxDVhhbXxhIyYdxwD3itCxI5D4d84=,tag:A6f6ZRH7p8bQRhLvwL0bsQ==,type:str]
stringData:
    api-key: ENC[AES256_GCM,data:h+brkoXiiYnzcN6Pm2FpugW56oo7GpBMc7qGK9d7Eog=,iv:oA/VwaXoBHmTog2kuAeyUE7gia5WI8UZzU4WdbFDl5s=,tag:ZRNt5qu1cAUHu1L0X4IeBA==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUHpINUhObm82NFBrSC9z
            VDQzamhtQ3U5Q0VJVFh3QzVicTNJTitHSVRjCjZQL21TOERuOVhDaU5VRGZtY2hu
            MS9qcGxGSisxeXpTTHV3WHVaVGVXZ0kKLS0tIHEyV0h6b01mbjUwQWlPY29paU5M
            RnZQOVp6aFRYYXNCMG1ZY3A1R25PUzgKQt8T1uoJ39cQYoXwRboUt4Qi0j8iWqoz
            CxBxxyn+CKCYHi6WBL8fylJVHrZ9V817Z93gIoseKV9KjnKAAuQJtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T10:46:24Z"
    mac: ENC[AES256_GCM,data:pp5YUbNIvJn1H4BfPb7ivPkxZVli8odPfBB11RysOOXaO9adxSh5a8UZJ+ikLiuF36Yp71xqWJDm1IAyEBSjo0WwzjDkUH3osDv4/SQhnyF9th19R/C7/E2Db2YSwf39RYRQ6fD3dMTVmWEkpJQZ6fdpcChzzmmoFF5eI2TR2G8=,iv:W6Fs5aOxMcqKdzw72QDob6PZJnXfrW3ClG7QZKHWE9c=,tag:SksC8jmJWBJ2mUHHEz9vjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
