apiVersion: ENC[AES256_GCM,data:F7A=,iv:tsJJlQHLn65m4XMQZjtwNBddB2UwGl2vZTeZK+DgPCo=,tag:5KjRaA+Iwn0xOH4Xq1+q2g==,type:str]
kind: ENC[AES256_GCM,data:RAANKdIY,iv:YnjW/FkwILkEVqiW4ziA2sLqX0EEDVILqoNjV5TzlfM=,tag:Z2eiKgnaP22d6lfqUDNoog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:glgFS5OCKaiyO8AVfEH+j4QLYRvcU76aJ9G53VmO,iv:+lSFRFQ86uErWE0GhA/o9n2eBINzWoxQCsot9V4Vu0c=,tag:TFnacIn1cUsS8jth0xjqrg==,type:str]
    namespace: ENC[AES256_GCM,data:2IGvntLdlHU=,iv:3/kw5lmZdYY7R+6lzL5Tw43aY0+epx4PwIWjdfvLsCE=,tag:mrEW0qw/cD4DM0wR3fOP7g==,type:str]
type: ENC[AES256_GCM,data:WQaAGUze,iv:GAj7NhU0sF3LfKbn4cehHhGGfJ10hVeBi1/FnhxOWTM=,tag:PTFuntPgrJjEa2vchzVTcQ==,type:str]
stringData:
    INFLUXDB2_TOKEN: ENC[AES256_GCM,data:r9t2Tg5AnzIrHAQmYPXK/hmNC1DHhbbmW5Pz2Gmm1ciDzlkQNGFQzNqIMzjotHiIUpy5ToRr3oUerdK5KuXYLGiflku4HdQAOd6SkrXC5GaBtw9J+KPAKw==,iv:aWMzU12a0Z+bdwXtRx2IxG/4OGNHxtbuasUeYOr12LM=,tag:5IqT9IjrfC79FrnQ6nYh4Q==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXbE9lUXhONmJsS0ZoOE1F
            UmsxZVNXS0VwODRKMXI4d04yMUlHcUE4YlZjClFyR0I0V0QxaWl2RXR3MERWV0xF
            ejVuOHBLMWc1U0ZVV09SRUh5WVpSUFUKLS0tIHRXbUdjMDJiVjVibEgwTE9PSXVI
            ZkxDUEt0a3lFOUxaOUEyMkI2by8wTnMKHfnosl/NV+6kFA8YvxYufXiinXVMiQK2
            HKbwvk7QndRcVEl+yQ0aRTZreY9kAtW7oQhIi7bGD3iM/LScD+Fdiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:52:55Z"
    mac: ENC[AES256_GCM,data:4Q0SY1therPogs8TNYV5zF3Lgf+egiL+9uu5d/4m3KtPGMzW8g0jtFntMXn2evFWMZr7xf5wsVja3DjGd21ADPu0tlCaPL+N3RMKdGEMc8G67WMEi7Oxbind2YT84KojB2358HLrdyND+tU5i9ZAY3uKGiI2cjFAT7tTj8187dA=,iv:ub6kJYQfq0AFK6eNQ2WVMdp4jPoqI8t8SkMFNB9uBYs=,tag:fwMYkjkD3KAK9PLIhER9yA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
