apiVersion: ENC[AES256_GCM,data:JA8=,iv:YC9uT4ZMHFDGkN4VU5gmKsKVo4a1H1DEUHXMyZWsD9w=,tag:yWaXm4/w/0x2D6G9+KoHmw==,type:str]
kind: ENC[AES256_GCM,data:RN8FD5Pv,iv:xBY+RwQQ54C9pkR86KaTt820AnYsxYGlU7/kMMgyFEI=,tag:U1toMtrDr5S/YssNx+w0kg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:e6n2appZowIfCxaxzvtVVSV8cbNHGyeXPQ==,iv:oenvYOXalVVYMApykOh/87h6YvhdlCji5AN1RHMUU9Q=,tag:6+Og6vGRGIirKPgWQ+19dQ==,type:str]
    namespace: ENC[AES256_GCM,data:1LavmbHmiiQ=,iv:yyd6+Aem2ToiLTb9PrS7XyqvAwbIKVWro9eKJkrtN/A=,tag:CX4284VpPEHGwqYGd7UjAQ==,type:str]
type: ENC[AES256_GCM,data:huRaZ4n3,iv:tkTetkyqu4S1CO/3nJP71+QiTXurZHRRENXpb/nIZ+U=,tag:/tLt5xa7Tm7Aoy++BmmInw==,type:str]
stringData:
    MQTT_USERNAME: ENC[AES256_GCM,data:A/2qPdFugM9ZomG3wAKDXA==,iv:7nlbI77/9wizq3WBHr/ureZZI0zuEm5hHg5KRoTRFZo=,tag:VwFzd557iNEeLymLKm1TZg==,type:str]
    MQTT_PASSWORD: ENC[AES256_GCM,data:QD51os9ur2VrwFiQ1I6WqPsPyNOEo9Qh9vQAMbWheE/RCw8RW5wib90OpEc=,iv:TpzpG5ijzkzp54Xdlt/0pFsTq8cYwduQq7p/da8uO1g=,tag:xs8ahaTqWJGgVdleNFBZJQ==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMXJVa0NJK01lVUFIdDd6
            NVJ6L2cxZ2VTUklOdVhhVE5DMSthZE5ZNWpnCnRIVEJUQmgxNU9wcVk3T0Jyd3FM
            bE1zV3h2YlVhelEvV1ZhK2tzdjF1V28KLS0tIG9zUThrd0JEcWZqK3VOcG5SbHkv
            UmZuTEFBL2p3aE5YWk9KRmdhTHN1QlUKxRD8Db55ozJzKC9yWanTfp1U67E5YQwY
            MKExxE/PeXPSI1bmS3LCl01iJT126LFYF1gsM2ZuY/j9QZ9RFd4n6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:53:02Z"
    mac: ENC[AES256_GCM,data:Rzuj3eudClmibWAuV85TVY6+vUa3WxeXgFX0NvK2WRfVrB6qKjfoj2fOMpWWHor0jw5l3y3XIHBLR6uFeUP+cca0tufFJrzZQl8V1MDlUkOZCvKrqCYJTUpuckT+SiEC7oztIgKuqYK8AzygdUKMt8j08CI6i2wMIn9sFZAHiLw=,iv:QMeZurxAZybVR/O0W8uQjeYHevFbCqA6seZK8m7JM74=,tag:OiS0WEH/vkx5NApHW2ZG8w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
