apiVersion: ENC[AES256_GCM,data:7kI=,iv:wbs/fKGoxY7Hi9owEcA0xPeCNViNG1opuARH0zCt3n8=,tag:Oc8Vo3/mh19ouPSMKPm7Lg==,type:str]
kind: ENC[AES256_GCM,data:1FdVySgR,iv:ZMi+Wp8bf5nMq92g+wbYO1XBxExk1XtoemJIKB0dWFM=,tag:NcBW3gS6NyufPJ36opOMSQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QutRrK4slnpyEKH7M/QSOLdzWfAEqnloc+uNGaG6bhc=,iv:rS4EkMfzczL9mKrA69GJ04/eWLNHdlPOt1bZRz9WWII=,tag:Sz8Kbj/pCCrHvdHpBc8q5g==,type:str]
    namespace: ENC[AES256_GCM,data:+HmCHTmYPA==,iv:bQlZ2mlQAjnK+/FoL/3JcdJVDMZEbRg0n7GbzP3S9Qg=,tag:FfUeIdODw3fKG3SuZI1iFQ==,type:str]
type: ENC[AES256_GCM,data:a6k2g0+k,iv:M5e5Gbm37tLOHowAT+2kpkJRMTIEGjCOdafcyTVf+ag=,tag:7AZ9dWB1nkq3YdLko1PyHg==,type:str]
stringData:
    SECRET_MQTT_MIOT_BRIDGE_USERNAME: ENC[AES256_GCM,data:35vg1uS+YdgPF+hd29cG+w==,iv:7GPDvpzO8GGfEG4NvmrP1LYfBeH01hUd/rHqna8n8bg=,tag:Xt5bhtsrnTkAYXddVFXvmw==,type:str]
    SECRET_MQTT_MIOT_BRIDGE_PASSWORD: ENC[AES256_GCM,data:v/ruB0ZkiqFidWatHbCmqdB1fh6/1XjS6GS/74Qe/qFDTIj9aFh5UOBc/DbZ,iv:ewCOn/TfyJtH2v22jf1JNa0Ken0ktM5vuZR8LZI3PHE=,tag:7yV5f1cohTl/BDun8WUYzQ==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMVZpMll5dnd0WWFMQUFI
            bDA3QWVlc01YVEVOZHpRNHBvSnEwRTNreUhrCmRPYnQxYVc5c0o4Um93MFIzRVUv
            VjN1U0t5bkh5ZVpOc2ozSDJOZUtMRGMKLS0tIHBqMHlSbTRVOW82MkUzK0Y0bjRl
            SUZXbGMzOXVIU2JUbzRIVHFnWWNiaXMKPDtao57N9KG6gtPJ5Yb4e2bKgh5lwxEy
            elzgENJ/tW7/w4IJoK+IOucLkDqP2M6qLKz/k/oi2a+OdsoTH1g7fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:27:01Z"
    mac: ENC[AES256_GCM,data:pbyFHuw3kId4nuenjJeKkDwyjXkDhdZsSlF7awDDENo5Sx2UEXXOxudesKLGQaSsK1fHM4JzSfRgvFnUj15I8vbnoFKig11zvbaLa4xte8D1zxH7pVj3BprLDhfIhY74tKWud652Mc1X2b54AJHL976M35HES+P94s+ezOh9Tcs=,iv:vg7EJ2HM5DJB7zUiKVmw2R46cQTzlg2zSUXeRMfq8AU=,tag:DySWa+ipsNavkB57LgT9uw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
