apiVersion: ENC[AES256_GCM,data:Hcc=,iv:gBKM6YfJNLdVmGJo9tMyKHjuqJyMw5aR/z7HcxCr7fM=,tag:MxiammtWkZ1Zezk265bliA==,type:str]
kind: ENC[AES256_GCM,data:FnQT8oJ6,iv:dZTkSWhAnezCVc9P3Up5Bf9rcJhVzdJmcl8mDVaY5H8=,tag:qXSUSYuXFADbz4lWE9j2DQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jKihPR0lsiNs/56XD8k/uVTLNKdulOyEgop6m1btwPOFuXk=,iv:nvcioHXPPTNaKM8hcYQ1vq9W0GBUYGhlCD69TjKVbDU=,tag:8Fn0HJNJbiE7YAvLbT6xUA==,type:str]
    namespace: ENC[AES256_GCM,data:4OaqMzl9Kg==,iv:Zw+rl7xO7Hr9tIkzyEIGAK90l+QXcj0qYGSW5kJtUEE=,tag:Oov4zKm6G6422ftWYHuAIQ==,type:str]
type: ENC[AES256_GCM,data:QugMjZE/,iv:bH+kwzIXcqyzELVhAop8f+IBQfX3GJ7WW/eQSiKi2J4=,tag:EtbQR1sLDsESPEG7lhKSpA==,type:str]
stringData:
    SECRET_MONGODB_DATABASE: ENC[AES256_GCM,data:UZo1SOs1hf5lUw7n1BvmpZ3/oA==,iv:Dfz1J3zcp8TAtpqiAZH3vLjpBYgB2B5zIxqihRMY65Y=,tag:Y2Pl2l2wEk+/4MY41kRzQA==,type:str]
    SECRET_MONGODB_PASSWORD: ENC[AES256_GCM,data:m4MZtvkxDZN/WPr5Yx1Qv8gPENtsfjzK,iv:UQeE220RlGkzOorinqJO8mNw/oVKsbGxOuT4Z4vdRe0=,tag:t0W9EyUfmbyeLkySipiaWg==,type:str]
    SECRET_MONGODB_USERNAME: ENC[AES256_GCM,data:rrTn8dsdgl0pzKmsNnxK,iv:AXk57tee8YJzxWwPkN9kDBiaPrQFcPsDkN0I/n63aP0=,tag:0H1LJHbMVuVid9jprmvg5A==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRER3aElrQUVtbHRQYld1
            SVZPODMvSFlMVmVZRkZWZXNvMUVoZXlIdGxVCjJpUHNUcjhYY3BhVkl4QkpaRERL
            YVVEaTFzblRxMlhmaUhBQVdFZXMwR00KLS0tIFNBb2Zpd1dNOTdwSzZBSFpHdHlF
            bU1KanRrNmQ0UytzL3J1RmIxUzVKbFkKQkNjYGRd8ES2DUrxrYY801X29M0FgY5P
            V1kR+nHBUoByV7zF2s62xiL7tjJPUVJdDfw/wB1rbJYiawqoWZ4lug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T15:26:52Z"
    mac: ENC[AES256_GCM,data:xkq/cuSBYDLb+bL1beXZU1P7NgchCxTqpi2W2gfxLTLbe0Kxc/YKdavtY47X7MB2bJ+07HXJSFXUfLxbakuwX2abXmtBRXqjZ8rkU+CW0UT3dSkYns4elr90MZLhbY1m/MSL9OdqbxpSwui9K5KJYGNGMhxNJvsmQURnFh2+do0=,iv:UX87jKHunWfDEX5Oka+kZH9l1VQ3ItgdPWtrUYE/rOU=,tag:b5x/+tm7X9RVL1jRR1A9rw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
