apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miot-bridge-api-iot-production
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/radoslavirha/home-server2
      targetRevision: HEAD
      path: helm-charts/iot-applications
      helm:
        releaseName: miot-bridge-api-iot
        valueFiles:
          - $values/helm-values/miot-bridge.yaml
          - $values/helm-values/production/miot-bridge.yaml
          - $values/helm-values/production/variables.yaml
    - repoURL: https://github.com/radoslavirha/home-server2
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/radoslavirha/home-server2
      targetRevision: HEAD
      path: k8s-manifests/production/miot-bridge-api
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true