apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      chart: external-dns
      targetRevision: 1.20.0
      helm:
        valueFiles:
          - $values/helm-values/external-dns.yaml
    - repoURL: https://github.com/radoslavirha/home-server2
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/radoslavirha/home-server2
      targetRevision: HEAD
      path: k8s-manifests/external-dns
      plugin:
        name: sops
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true
