apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-prometheus-stack-grafana-datasource-tempo
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
  labels:
    grafana_datasource: "1"
data:
  tempo.yaml: |
    apiVersion: 1
    datasources:
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            filterByTraceID: true
            filterBySpanID: false
          lokiSearch:
            datasourceUid: loki
          tracesToMetrics:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true
          serviceMap:
            datasourceUid: prometheus
