apiVersion: ENC[AES256_GCM,data:uu8=,iv:g+OFBWE7yIsAvve87tzN7rEFRTxz+psJrQfkcI1bwX0=,tag:dJ9EPAw2xs537Ce9cJH2lw==,type:str]
kind: ENC[AES256_GCM,data:r95E4CMN,iv:NroPKIs8lMxp2ZAOjLx2yUwofNY9e2eyFyjVaLiZ59I=,tag:rmzeWh6D/YgS4T0KMOS8ng==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FE+Kg6wLStpCTDlJtcU19AAP+2+ha17K5zQh9WqMVrTIyoqZRFa6YjzTLdMbO66OOaqVw4FPqg==,iv:0HC84+NQXSXpAbpjHDB3WuL1TymtaW8TEEE0mRMN/40=,tag:9ckONbBrDHRNdQHGSgBfVQ==,type:str]
    namespace: ENC[AES256_GCM,data:cKIOlKZ/GHg6/w==,iv:Xdl4zCO0GKNsIU3jNQ5dEjV0h+vMj2yKrpBGB50R8tM=,tag:WQbNMO+iy0MmCKk8K+Ob7g==,type:str]
type: ENC[AES256_GCM,data:QqGTeTME,iv:CLPSHJrKNI/YWaPZ+uh0BVkUr7CncYj8MjLAfylGH1s=,tag:XeE5GFui44eVJWDO/hMShw==,type:str]
stringData:
    INFLUX_DB_2_TOKEN: ENC[AES256_GCM,data:9HfLjfUYkcMV273i+GAxYdViA8BSbRJ3BLCD3jaTMAWG0aayN81j7qlfEKx9ADq2FoyCHd9l2GCojgEAwilpQa3xePex42X/4EU0UhScvGaAa7wanDYnqQ==,iv:2yxTq7zW1npbHMLmoPlODsxlvM6MS/2yYFDgvuGMrYk=,tag:3yjUwnaQXB+1tu5YLTzyaw==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdHRqRktNaVhwVG9MTXVI
            V1FEaVQyYUNtRWZXRHExSERFRWREcnFpMVZVCkZzR3RsOG9vVWdFdFB5OThwK3Zw
            Mzk3VFB6WmM0ZDczRzJJTmRtZHFVZTAKLS0tIG9tZTE0d3h3Q0MxbU1rUXMzaFQw
            T0htSlJVUEk1bG90ZUhmQi9MRzNNT2cKz+qFH/vaaaB4KOfEJkzbOdc/WnZJprD5
            /Ke0mGNoEnW2jwqlRbL+3CrDJh2iZia5uQgKJ+7IdPKI4X98IJsYJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T14:22:01Z"
    mac: ENC[AES256_GCM,data:Rv66M4t4+x03to4r0ZRHEm5JViwd0BfipKd2Kx5afILEcRAbuxrnkIDbdiEA+grWV2ayV6OM+BQPk1jjVVEXc+CaHvCM0DZPlVPJtUYZ6ZvAvYINTZxlD1J3Q4G87g9Te5j8JIbdPGanknPrFNNVSmUTnnKtvRVmuDuyCk4Lh7s=,iv:08aR7QGKLy0mcP8hP2AsrsPQIk2VeTarLFqrTaCWkgI=,tag:ochJzrWPe5b7XoemTn5cgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
