apiVersion: ENC[AES256_GCM,data:cAY=,iv:7/0U01eL32B49UQuPX6u0nodiD0hi5eEJhh/++27Zv4=,tag:y+X2VBHSYQfotGC2+4mcuQ==,type:str]
kind: ENC[AES256_GCM,data:Iz95S8z/,iv:0heRe48KT7cEhToxN7QfvW5AjUQvXb195j36HsebASM=,tag:UnyokI/PPtRFggqHsFU4FA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nfd3In/dss0fhKJyyIERcyquPEeVGREk0Hz0rcP5EPVCDKUztHQOdQ==,iv:SeKcCuTFfBVhWwRRoIIsZX7Pdi94+ymqARvcoz8aRAw=,tag:gj7xa+0PTndJGIUJ9TUnWA==,type:str]
    namespace: ENC[AES256_GCM,data:bjw8xRnP9Gl1Uw==,iv:cwE81v6ZljilikzfB+jqbf1eYx034CxrIOCHHWVfeF8=,tag:KqalhpdA5969tJLBofbwEA==,type:str]
type: ENC[AES256_GCM,data:CqM8Mt6X,iv:V4EY3lfJrwHJw66fFadra7l3qrn2s60ec1CnWknHoRM=,tag:qfiJpQ18rycKNhHl5L07kQ==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:Q2843rI=,iv:6R85vi2H6zssBRxpmzuYXYksV1ecoAU+Z6f/nyUPFos=,tag:lA24hqHAOVx2iaFVC85lGA==,type:str]
    admin-password: ENC[AES256_GCM,data:ORlYhdg5KMoW9uXNYJI=,iv:DvbcPCJ5SLlTf33Y90rOMb3+OPU4Z925pPKRioZKjFs=,tag:HjQmGYatYtcB91HgMAOBsg==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZmV0d2xYV01kc1RuSUxz
            SEwwSExzT0tuV0JCcC9pSWxabGxiT0xpZ2lVCkVHeFhKOWs2dUZCNFRHOUp2aXVE
            MGIxMDB3YzZmY3Z0cEpvMFkydERYWDAKLS0tIFdtZWt5dWtGWitZRFFvQnp0NDlU
            U3FMOUhQK2g3bjBwcys5TFlPb1BFbFEKd3gDiAWMI4iRgKkoVR27o51w/t+8ejUB
            xGYoQST/7jswWRB5gk9a2xtWTg6APpvn8bbzsidSR2oIfSzjJvDXZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T14:21:56Z"
    mac: ENC[AES256_GCM,data:nlodb6LO7Tc+yJjHku7mHfw2syxxzLefOhdgOEq6Qas0szTO7DBKpLsg4AHoovy9abD1d4rrOTBvVEzpds6W3aBD8XJeU2kO1rWcFVl9wJ1XBJ3eJptr0j/tLhLPtgAll9omkLn0rUTD7ZecJ0S4PvWdhiFVkjr5q9Bc+GrK/2s=,iv:oQeIPTbaFr3rfqHfb+4UwoZDIZVS+YnWm9m1BfMc5MQ=,tag:fqpw4kwEkHySNMZ96vgj6Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
