apiVersion: ENC[AES256_GCM,data:WcI=,iv:/rphkonM8a0XE11B5BfLpWkZf5a2d/5rEZPT4rrGXmo=,tag:Xzw3ux9jJ2X3g4O2y3mAhA==,type:str]
kind: ENC[AES256_GCM,data:HbwpTvfk,iv:UmnxhjiInwdqoOpXOKV5ewGKBwJ4/hG4UsznW7QIUck=,tag:fxDJGJi96xJzlJmQ5osLKw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Gy4rRgr8yA==,iv:QKb1MYkLZe3c60GgVo+z0xBB0bHX60iP637UHShqEPs=,tag:gjpIqO4wGSRtIkzGS+TsSg==,type:str]
    namespace: ENC[AES256_GCM,data:B3YyjDnNyw==,iv:gc7A7wlT+RwHb9x275koPIra3iR+fatI9/2LpI1+0gM=,tag:4vVp7tHqCcb9WTZCMPPu0w==,type:str]
type: ENC[AES256_GCM,data:8e6Kfijb,iv:iqG1R0WWONb6lj7mRfvYdMLQWeCNe+p04B1ThQ8a4ro=,tag:LRgpT2zSxOyD7CjSQb9tNA==,type:str]
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:uX8TwCW17Vo3YOoH3fEMihZwXGVRoPbE,iv:To1U3P5O/0g1q88Cwcdo5B9H2DzGd4Gut/y5O0DwwXQ=,tag:WJVps/tPl2B7dOoMI1v6Ww==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByaEdGcTR5UUYvRzgwZDFG
            Z2dFZGZxaStGdUhEWnJGV2krRFdVUmVoanlBCk5HTU5WZGNFbURoSlYxR01udEdG
            YXB6OHZXUHJOZG5saWJOUHFSL3hPNm8KLS0tIGwxczdFV3Ivc3N3THFMdnpScXF2
            REZVeTFxT0UvKzFjRXBoN01wdnJhTDQK7YEHSpes0ql0iTgTWVP5YrFU0C4+QbAV
            UwEVuh+HuBXmhatOkH28PBAaU2Y7DLzoaBGmjIkVLQxQ1EtL6y6KBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:58:55Z"
    mac: ENC[AES256_GCM,data:zubdHgnkhmMLQbCGwAh8S/FyoPRjI2PRQaAgrTIDidRZVNaB82euXRUeJJ5c6/9mEs2lz6Rm2NUVWHiJP4V8xNhYmMRtfe1pJQ+DnPX2tc9yTl9Vsq7ZS0mgNj7hGth/rgxsfE2K7xNHhtVaUiArzy353jrRGEwhKUGptNl0ipE=,iv:gx5YaxXUBJ44svWUIh3J/Yv33ijhPpwFmZgcL7ICDHg=,tag:tHlUtmF3xKL50TUeokTP8A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
