apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegraf
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.influxdata.com
      chart: telegraf
      targetRevision: 1.8.69
      helm:
        valueFiles:
          - $values/helm-values/telegraf.yaml
    - repoURL: https://github.com/radoslavirha/home-server2
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/radoslavirha/home-server2
      targetRevision: HEAD
      path: k8s-manifests/telegraf
  destination:
    server: https://kubernetes.default.svc
    namespace: telegraf
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      selfHeal: true
      prune: true
