apiVersion: ENC[AES256_GCM,data:qp4=,iv:gI3eqCdC4dxO5O3RuNYE0ZoKIdOsa+9VVTngtfiMq/U=,tag:z2lzsB7hyb5fbP9bOhHO0w==,type:str]
kind: ENC[AES256_GCM,data:v8vm4AQ+,iv:zfaWvd1HIVAHYGeXwKo9IqFM3ypZeeg+ZSmY8G47m0Y=,tag:z7k7m1Wa3zLAQcZ1vRTIXw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:0PT1PJb37jfh,iv:wCviufNnBNNB/+OOELDqekDTJpgqxIF1KCyGcp26lGI=,tag:TGbDEvVaKwIsa79VCyD5Dg==,type:str]
    namespace: ENC[AES256_GCM,data:kI8Vs6pQtmVwDQ==,iv:JVvUmWx0RLCfvefVFWW5WqA/2uzoya4qIkpAkQ4AevE=,tag:rODvtwm43Nh6Aj0pcv4K+A==,type:str]
type: ENC[AES256_GCM,data:Gm8FVr92,iv:vrlIUAHekL1buY3KMMChc0bfCmTy6b8ldJUl9uEWl7A=,tag:4V5q9pDFH4dYTemtZB6P1A==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:Db1m7Mn24Vsyee1KGWpGjv0dJgMVL0xg,iv:04nNkTPCF1XYwl0rPn5VnfGSRIWtVj8Pd5tc8d+l0q8=,tag:jzDDQyJQPRPqtZtarpvNIg==,type:str]
    admin-token: ENC[AES256_GCM,data:l1f9Dm+PL2IK/Ao2QVqa5NcXDKNvuRtk,iv:uyli4IO59HqIYccQ9HloPQZcFQiOOH22684Ew9YWetE=,tag:/JNG+fIqs5nGTm1/WoppSg==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabFFZVFkzMVpxZnY2ZlBw
            eHpvRVlNSm5mRmJVME92RDhBNFVkTVRSblJrCnpBSFBCSjlOVjYvTkxnUnFUd3dv
            cXB5VExBWnY1R0JteS8vUWhYWGNJZGcKLS0tIHhlTFZuZU1MeU4yUXZNb1lrMi9F
            b3VBcE5vUldFMExHVHdGaEdkWnMxQncKWlWnXU4A0D5QHhGmFjZPqWUlesCrtxZU
            eeYN6Wm9/DyqrcQIzd+te3MlQr7wQr/4ZeOCl6czthRVLXDAPNBKBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:23:33Z"
    mac: ENC[AES256_GCM,data:zGxi01UHUJ/YiVk9wc0EQXgOJJVOUbT9JGV/UbAdwPwYzsJPrT/+Pgg7r/310Vwnjq+oQJMLVknlhYEYzygWr8TD+3ke9/4ajy+sx4C8PwiSTiAV0vtE9KqEnRUrcr8YCaA+LmEq0ZKSu5bKlUWEAPB7g55iXhOfNfNYsIV0Moo=,iv:D2cuFwawF5LJ4E3lkAJkx0W08g4FBEhkzJUL4WUqmes=,tag:fnel9d4ky5glb2+swvsUfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
