apiVersion: ENC[AES256_GCM,data:oxo=,iv:yt4HEJfTOMZe2QZmNDPlcs00nneosJ22YE3k+n/9xJU=,tag:1TRv7agZOUtEIdXb/y5djg==,type:str]
kind: ENC[AES256_GCM,data:xG+PDD+I,iv:8Sp6hwF04Kw4T6rdB7HLdCZuFVIpVB2m0FMe/rgRwmM=,tag:QfcZwc2TEsOmDQxQzO59ug==,type:str]
metadata:
    name: ENC[AES256_GCM,data:o2PUCR9g4mo6,iv:xTWjmkj5Bg+/oI5ejmNRwCxoEY+3yb4a/511UwYVfdw=,tag:UCIloYQpcBrCvYIdGVeqfA==,type:str]
    namespace: ENC[AES256_GCM,data:Gxeua9lwoRsg2Q==,iv:TjvPZJ8Txowaf50oBnh7ksvtA+1SQpJavDIxFH3Vsj8=,tag:rGdqRZAI0FvdHvd+arWyuA==,type:str]
type: ENC[AES256_GCM,data:o/w9C1No,iv:bLDp8sGDswuVIpETXNgEDD90h3znilgY5mWgqSC7vqI=,tag:V5eEl6dom/QnYjxnGlyqlA==,type:str]
stringData:
    admin-password: ENC[AES256_GCM,data:aNU+aVbethY4JyEg7KfpxvSZ5Q2evzmD,iv:lX0Y9XRzNj6V66Ot1uT/wPk/iI6S2cp3xSfu1/87jNo=,tag:XTJoE77cdOSZuT/hsHlYQA==,type:str]
    admin-token: ENC[AES256_GCM,data:rjZUyKwb+ERrVdm2+NF+VNt26RPVutgi,iv:DEDLieyh5bk9GjdJS56OIKYnhSW4jEOgAUTEPou1xVY=,tag:oeBU70S48ix6Ae7z3xfg1A==,type:str]
sops:
    age:
        - recipient: age1te8tx6p52w4jwh7gvrsze2yydy52uncnsxe9g8pk7n65emlvl3qsyrwjc5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOXo2ajZjKzBDV2hFYldl
            cWQwZFhuRHRRUTN4N3Z6czRhNXVZNHg4c1RVCnA2WGJVanBIYWhJWW1WN2lrNysr
            cXJmL1BIZVhnd0k4Sm1NZWMrZWFRVEEKLS0tIEJGdDlMbmxlcFRHMUl0Wm9NelRl
            amxQb2lXb2lEWGpTWXdpYVc2SHZQRU0KB/zGF1zOoRZ5d/qXrvJf7rzHBhLo0+W9
            LturOtnS5s2MnQS5XsUL2+tknyZtyA9yk99fhg5IoL5LJVCYsl3OEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-09T19:41:01Z"
    mac: ENC[AES256_GCM,data:99rXLB3M+hP4sHz4myPbo5f3Fxw2w8zKrZ6Rc6z4J4YgxqqGQCEtvYfYiaEv9UQSV1ON0CAEm9o6By2rXroGqIttZs2WRe/oGWT8Pm3NlKHLQyek04pmCIt/iSOQ+A1pmnfURdyI+NbWRceupE0oMMzFTukT83YffAOU0uLQ8aE=,iv:a1L6bJAQla5C4z7akLWHY8egxmrVDRi39Rq7ZsWz+CY=,tag:9NKlcwXn5vgizUZfN/0KJA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
